### ISSUE TITLE
Opening printer settings disables existing active printer

### ISSUE THREAD

**Issue by ibnesayeed** [elementary/pantheon-print#17]
I have a network HP printer that I have configured, but when I open the printer settings, it disables the printer. The enable toggle switch is always set to disabled when the settings window is opened.

**Comment by valentinajacob** [comment]
In the base (master) image stop and disable "TP AutoConnect Service" service, then shutdown, take new snapshot and recompose pool
Use the view client adm template (vdm_client.adm) by adding to existing ProfileUnity GPO. 
Then under user configuration>administrative templates>Vmware View Client Configuration/RDP settings.  "Disable redirect printers"
I m facing issue in my printer and its  driver issue it is going offline and I m not able to fix it up after going to the [brother hl-2270dw driver](https://www.brotherprintersupportnumber.com/blog/tag/brother-hl-2270dw-drum-error-light/) my printer start working and now I m really happy thanks to this site

**Comment by ibnesayeed** [comment]
It looks like this issue has been fixed, so closing it here.

**Comment by ibnesayeed** [comment]
Apparently, https://github.com/elementary/switchboard-plug-printers/pull/104 fixed it.
